// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getAll
List getAll(NumericVector fragRef, double frag, double limit);
RcppExport SEXP MsatAllele_getAll(SEXP fragRefSEXP, SEXP fragSEXP, SEXP limitSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type fragRef(fragRefSEXP );
        Rcpp::traits::input_parameter< double >::type frag(fragSEXP );
        Rcpp::traits::input_parameter< double >::type limit(limitSEXP );
        List __result = getAll(fragRef, frag, limit);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
